theme: minima
title: Robonectics Learner Docs
author: Michael B
description: Documention for the Robonectics Learner Projects
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
